Cargo.lock, Cargo.toml, src/error.rs, src/reader/decode/rle_v2/delta.rs, src/reader/decode/rle_v2/direct.rs, src/reader/decode/util.rs
Remove zigzag dependency (no need to pull in extra dependency for this)
Remove usage of `rle_v2_delta_bit_width()` which is duplicated with `rle_v2_direct_bit_width()`
Refactor `read_vulong()`
=> Refactor varint handling

src/arrow_reader.rs, tests/basic/main.rs
Previously wasn't able to read past first stripe in ArrowReader, fix to allow
=> fix: read entire file with ArrowReader

src/arrow_reader/column/boolean.rs, src/arrow_reader/column/present.rs, src/arrow_reader/column/tinyint.rs, src/reader/decode/boolean_rle.rs, src/reader/decode/byte_rle.rs
I'm trying to implement the list datatype. However, I found that our present iterator relies on the `number_of_rows` of stripe, which made the nested lists also rely on it.
=> refactor: refactor byte/boolean iter

src/reader.rs, src/reader/decompress.rs, src/reader/metadata.rs
Initial attempt at refactoring how file read is handled, as stated here https://github.com/datafusion-contrib/datafusion-orc/issues/42#issuecomment-1812164415
=> Refactor synchronous parsing of file tail metadata

src/arrow_reader.rs, src/arrow_reader/column.rs, src/async_arrow_reader.rs, src/lib.rs, src/reader.rs, src/reader/metadata.rs, src/statistics.rs, src/stripe.rs
Part of https://github.com/datafusion-contrib/datafusion-orc/issues/41
Start introducing some of our own structs/types to represent their protobuf counter part
Allows us to have more control, such as ensuring fields are actually present (since proto has them as Option usually)
=> Refactor to decouple from relying directly on proto

benches/arrow_reader.rs, src/arrow_reader.rs, src/arrow_reader/column.rs, src/async_arrow_reader.rs, src/error.rs, src/lib.rs, src/reader.rs, src/reader/metadata.rs, src/stripe.rs, tests/basic/main.rs
Remove Reader struct and combine it into Cursor
Also implement the AsyncChunkReader trait
=> Remove Reader struct, condense into Cursor

src/arrow_reader.rs, src/arrow_reader/column.rs, src/async_arrow_reader.rs, src/lib.rs, src/projection.rs, src/schema.rs
Closes #19
Encapsulate projection logic in new `ProjectionMask` struct, akin to how parquet does it
Hopefully can provide structure for future work for projecting nesting fields, see #52
=> Introduce ProjectionMask

.github/workflows/ci.yml
Seeing CI failure: https://github.com/datafusion-contrib/datafusion-orc/actions/runs/7360911822/job/20037635643?pr=53
```
error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/random_state.rs:463:5
|
463 | /     fn hash_one<T: Hash>(&self, x: T) -> u64 {
464 | |         RandomState::hash_one(self, x)
465 | |     }
| |_____^
|
= note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information
= help: add `#![feature(build_hasher_simple_hash_one)]` to the crate attributes to enable
```
=> Switch CI toolchain to stable

benches/arrow_reader.rs, src/arrow_reader.rs, src/async_arrow_reader.rs, src/lib.rs, tests/basic/main.rs
Closes #42
Introduce a builder which can create the sync/async reader, without requiring users to create a Cursor first
Also can be used to handle option settings (like projection and batch size)
=> Add ArrowReaderBuilder

Cargo.toml, src/error.rs, src/reader/decode.rs, src/reader/decode/rle_v1.rs, src/reader/decode/rle_v2.rs, src/reader/decode/rle_v2/delta.rs, src/reader/decode/rle_v2/direct.rs, src/reader/decode/rle_v2/patched_base.rs, src/reader/decode/rle_v2/short_repeat.rs, src/reader/decode/util.rs, src/reader/decompress.rs, src/statistics.rs, src/stripe.rs
Closes #56
Introduce generics to the integer decoding behaviour
Will now have RLE decoders (v1 and v2) for each supported Orc integer type, instead of a generic i64/u64 decoder
=> Introduce generics into RLE Int decoders

.github/workflows/ci.yml, Cargo.toml, src/arrow_reader/column/mod.rs, src/arrow_reader/mod.rs, src/lib.rs, src/reader.rs, src/reader/metadata.rs, tests/basic/main.rs
Resolves https://github.com/datafusion-contrib/datafusion-orc/issues/46
=> Put async functionality behind feature

Cargo.toml, src/bin/orc-export.rs
This tool is quite useful for me. In the futuree I plan to add support for selecting the columns and saving as json
=> #62 Added cli tool to export data in a csv format

src/bin/orc-export.rs
Added to the orc-exporter
* filter by rows
* filter by columns
* skip unsupported columns (e.g binary for csv)
=> #62 added filtering by rows and columns

src/array_decoder/timestamp.rs, tests/integration/main.rs
Since 60288cdee57f72dec84c3fd9f6085561568aad49 we applied an unary_opt kernel to decode timezones. This kernel always returns `Some` unless the date is outside the 1677-2262.
Unfortunately, even though the kernel is unlikely to return `None`, applying the kernel always causes the resulting array to get a `NullBuffer`, even if the source array did not have one.
In order to avoid unnecessarily adding a `NullBuffer`, this commit first tries to apply a non-nullable kernel; and only falls back to `unary_opt` in the rare case it fails.
An alternative implementation that does not risk running the kernel twice would be to check the `NullBuffer`'s `null_count` after running the kernel then strip it if its `null_count` is zero; but it requires the unnecessary allocation of a `NullBuffer`.
=> Avoid adding a NullBuffer when decoding timestamp offsets

src/array_decoder/list.rs, src/array_decoder/map.rs, src/array_decoder/mod.rs, src/array_decoder/struct_decoder.rs, src/array_decoder/union.rs, src/column.rs, src/error.rs
This is the prerequisite to support configurable timestamp precision mentioned in https://github.com/datafusion-contrib/datafusion-orc/issues/75#issuecomment-2130754391
=> Pass target arrow type to array_decoder_factory

README.md, src/array_decoder/mod.rs, src/array_decoder/timestamp.rs, src/arrow_reader.rs, src/reader/decode/timestamp.rs, tests/basic/main.rs
Mostly resolves #75, though users may want to decode timestamps as two i64 columns in order to preserve both precision and range. (Or could Arrow be extended to support i128 timestamps?)
=> Add support for configuring time units through ArrowReaderBuilder::with_schema

src/arrow_reader.rs, src/async_arrow_reader.rs
This allows getting the schema before building a reader; so users can apply transformations to the schema, like this:
```
let reader_builder = reader_builder
.with_projection(projection.clone())
.with_batch_size(ORC_BATCH_SIZE);
let schema = transform_schema(&reader_builder.schema());
let reader = reader_builder.with_schema(schema).build();
```
where `transform_schema` could, for example, be a function that changes the `TimeUnit` of `Timestamp` datatypes.
=> Add ArrowReaderBuilder::schema()

Cargo.toml, src/error.rs
This PR will reorganize deps for better maintain. Also, this PR bumps deps to latest, which will close existing two PRs.
=> chore: Reorganize deps and upgrade them

Cargo.toml, src/reader/mod.rs
Part of https://github.com/datafusion-contrib/datafusion-orc/issues/116
=> feat: Add opendal native support

src/reader/decode/rle_v2/patched_base.rs
For some reason, some files written with pyorc have a `patch_bit_width` larger than needing, causing the previous check to fail, even when decoding to `u64`.
This changes the check to only fail when the patch bits actually overflow, instead of checking whether they may overflow.
Unfortunately, I can't provide a test. Even when writing the exact same values with the same version of pyorc, the generated file does not trigger the error like https://softwareheritage.s3.amazonaws.com/graph/2024-05-16/orc/revision/revision-0c45576a-59f7-48d1-a9a8-2e5c64098905.orc
Closes https://github.com/datafusion-contrib/datafusion-orc/issues/97
=> Relax check on `patch_bits` overflows in delta decoding

examples/datafusion_integration.rs, src/array_decoder/mod.rs
=> fix: execute "select count(*) from tbl" always getting zero

src/array_decoder/decimal.rs, src/array_decoder/list.rs, src/array_decoder/map.rs, src/array_decoder/mod.rs, src/array_decoder/string.rs, src/array_decoder/timestamp.rs, src/encoding/byte.rs, src/encoding/float.rs, src/encoding/mod.rs, src/encoding/rle_v1.rs, src/encoding/rle_v2/mod.rs, src/encoding/timestamp.rs
Though the benchmarks are kinda simple, they identified (via flamegraph) that there was a significant amount of time being spent on next() calls in RleReaderV2. So introduce a new PrimitiveValueDecoder to enable batch decoding support, currently only properly implemented for integer arrays with no null buffer. Even so, benchmarks show significant improvement:
```
datafusion-orc$ cargo bench
Compiling orc-rust v0.3.1 (/home/jeffrey/Code/datafusion-orc)
Finished `bench` profile [optimized + debuginfo] target(s) in 11.65s
Running unittests src/lib.rs (/media/jeffrey/1tb_860evo_ssd/.cargo_target_cache/release/deps/orc_rust-53e462447a03afd6)
...
Running benches/arrow_reader.rs (/media/jeffrey/1tb_860evo_ssd/.cargo_target_cache/release/deps/arrow_reader-419fc98a1d304edb)
Benchmarking sync …
```
=> Introduce PrimitiveValueDecoder to enable batch decoding of values

.gitignore, src/arrow_reader.rs, src/async_arrow_reader.rs, src/datafusion/physical_exec.rs, tests/basic/main.rs
Since spark orc file format will slice a file into multiple orc splits, support filter out strip by provided range will avoid reading whole orc data file.
=> Support filter out strip by provided range

Cargo.toml
See #129
Do a minor release so `datafusion` feature will show on docs.rs especially because we reference it in the docs:
https://github.com/datafusion-contrib/datafusion-orc/blob/be8a685c25a028caa2aa8356dcefddee783349a9/src/lib.rs#L49-L50
=> Release 0.4.1 to fix features on docs.rs page

src/stripe.rs
closes https://github.com/datafusion-contrib/datafusion-orc/issues/132 .
=> skip reading unused columns
